import Head from "next/head";
import { Jost } from "next/font/google";
import Header from "../general/header";

const jost = Jost({ subsets: ["latin"] });

const LayoutMain = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>TEPI.MY | Makan Malam Tepi Jalan</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${jost.className} h-screen w-screen bg-gradient-to-b from-outrageous-orange-100 to-outrageous-orange-50 text-zinc-900`}
      >
        <Header />
        {children}
      </main>
    </>
  );
};

export default LayoutMain;
